School.Presentation/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School.BLL;
using School.Domain;

namespace School.Presentation.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService = new CourseService();
    
        #region Read
        public async Task<IActionResult> Index()
        {
            var cousres = await _courseService.GetAllAsync();

            return View(cousres.ToList());
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var cousre = await _courseService.GetByIdAsync(id);

            return View(cousre);
        }
        #endregion

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View(new CreateCourseVM());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            // Manual mapping (no AutoMapper)
            var course = new Course
            {
                Name = model.Name,
                Topic = model.Topic,
                Degree = model.Degree,
                MinDegree = model.MinDegree
            };

            await _courseService.AddAsync(course);

            return RedirectToAction(nameof(Index)); 
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var course = await _courseService.GetByIdAsync(id);
            if (course == null)
                return NotFound();

            // Manual mapping to UpdateCourseVM
            var vm = new UpdateCourseVM
            {
                Id = course.Id,
                Name = course.Name,
                Topic = course.Topic,
                Degree = course.Degree,
                MinDegree = course.MinDegree
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateCourseVM model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var existingCourse = await _courseService.GetByIdAsync(model.Id);
            if (existingCourse == null)
            {
                ModelState.AddModelError("", $"Course with ID {model.Id} not found.");
                return View(model);
            }

            // Manual mapping (No AutoMapper)
            existingCourse.Name = model.Name;
            existingCourse.Topic = model.Topic;
            existingCourse.Degree = model.Degree;
            existingCourse.MinDegree = model.MinDegree;

            await _courseService.UpdateAsync(existingCourse);

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
                return BadRequest("Invalid course ID.");

            var course = await _courseService.GetByIdAsync(id);
            if (course == null)
                return NotFound();

            await _courseService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region Remote Attributes
        public async Task<IActionResult> IsCourseNameUnique(string Name, int Id)
        {
            if (string.IsNullOrWhiteSpace(Name))
                return Json(true); // skip if no name entered yet

            var existingCourse =  _courseService.GetByNameAsync(Name);

            if (existingCourse != null && existingCourse.Id != Id)
            {
                return Json($"A course with the name '{Name}' already exists.");
            }

            return Json(true);
        }
        #endregion

    }
}

School.Presentation/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using School.BLL;
using School.Domain;
using School.Presentation.ViewModels.Student;

namespace School.Presentation.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IGenericService<Department> _departmentService;
        private readonly ILogger<DepartmentController> _logger;

        public DepartmentController(ILogger<DepartmentController> logger , IGenericService<Department> departmentService)
        {
            _logger = logger;
            _departmentService = departmentService;
        }

        #region Read 

        [ServiceFilter(typeof(LocationRestrictionFilter))]
        [ServiceFilter(typeof(LogResultFilter))]
        [ServiceFilter(typeof(CacheResourceFilter))]
        [CustomExceptionFilter]
        public async Task<IActionResult> Index()
        {
            var departments = await _departmentService.GetAllAsync();

            return View(departments.ToList());
        }

        
       // [CustomAuthorizationFilter]
        [ServiceFilter(typeof(CacheResourceFilter))]
        [CustomExceptionFilter]
        public async Task<IActionResult> Details(int id)
        {
            var department = await _departmentService.GetByIdAsync(id);

            return View(department);
        }
        #endregion

        #region Create
        //Student/Create
        [HttpGet]
        public  IActionResult Create()
        {
            var vm = new CreateDepartmentVM();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateDepartmentVM createDepartmentVM)
        {

            //Not Valid 
            if (!ModelState.IsValid)
            {
                return View("Create", createDepartmentVM);
            }


            //Valid 

            //Map VM => Entity 
            Department? department = new Department()
            {
                Name = createDepartmentVM.Name,
                Manager = createDepartmentVM.Manager,
                Location = createDepartmentVM.Location,
            };

            //Add
            await _departmentService.CreateAsync(department);

            return RedirectToAction("Index");
        }
        #endregion

        #region Update
       
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var department = await _departmentService.GetByIdWithIncludeAsync(id , d => d.Instructors , d => d.Students);
            if (department == null)
            {
                return NotFound();
            }

            // Map entity => VM
            var vm = new UpdateDepartmentVM
            {
                Name = department.Name,
                Manager = department.Manager,
                Location = department.Location
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateDepartmentVM model)
        {

            //Not Valid 
            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            var existingDepartment = await _departmentService.GetByIdAsync(model.Id);
            if (existingDepartment == null)
            {
                return NotFound();
            }

            // Update fields
            existingDepartment.Name = model.Name;
            existingDepartment.Manager = model.Manager;
            existingDepartment.Location = model.Location;

            // Call service to update
            await _departmentService.UpdateAsync(existingDepartment);

            // Redirect back to the list
            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        //  Department/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete([FromRoute]int id)
        {
            var department = await _departmentService.GetByIdAsync(id);

            if (department == null)
                return NotFound();

            await _departmentService.DeleteAsync(id);

            return RedirectToAction("Index");
        }

        #endregion
    }
}

School.Presentation/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using School.BLL;
using School.Domain;
using School.Presentation.ViewModels.Student;

namespace School.Presentation.Controllers
{
    public class StudentController : Controller
    {

        private readonly IStudentService _studentService = new StudentService();
        private readonly IGenericService<Department> _departmentService;

        public StudentController(IGenericService<Department> departmentService)
        {
            _departmentService = departmentService;
        }


        #region Read

        //Student/Index
        public async Task<IActionResult> Index()
        {
            var students = await _studentService.GetAllAsync();

            return View("Index", students);
        }


        //Student/Index/1
        public async Task<IActionResult> Details(int id)
        {
            var student = await _studentService.GetByIdAsync(id);

            return View("Details", student);
        } 
        #endregion

        #region Create
        //Student/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            // refill
            var departments = await _departmentService.GetAllAsync();

            var vm = new CreateStudentVM
            {
                Departments = departments.ToList(),
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentVM createStudentVM)
        {
            //refill
            var departments = await _departmentService.GetAllAsync();
            createStudentVM.Departments = departments.ToList();


            //Not Valid 
            if (!ModelState.IsValid)
            {
                return View("Create", createStudentVM);
            }


            //Valid 

            //Map VM => Entity 
            Student? student = new Student()
            {
                Name = createStudentVM.Name,
                Age = createStudentVM.Age,
                Address = createStudentVM.Address,
                Email = createStudentVM.Email,
                ImageURL = createStudentVM.ImageURL,
                DepartmentId = createStudentVM.DepartmentId
            };

            //Add
            await _studentService.AddAsync(student);

            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var student = await _studentService.GetByIdAsync(id);
            if (student == null)
                return NotFound();

            var departments = await _departmentService.GetAllAsync();

            var viewModel = new UpdateStudentVM
            {
                Id = student.Id,
                Name = student.Name,
                Email = student.Email,
                Age = student.Age,
                Address = student.Address,
                ImageURL = student.ImageURL,
                DepartmentId = student.DepartmentId,
                Departments = departments.ToList()
            };

            return View(viewModel);
        }

       
        [HttpPost]
        public async Task<IActionResult> Update(UpdateStudentVM model)
        {
            //refill
            var departments = await _departmentService.GetAllAsync();
            model.Departments = departments.ToList();


            //Not Valid 
            if (!ModelState.IsValid)
            {
                return View("Update", model);
            }


            var student = await _studentService.GetByIdAsync(model.Id);
            if (student == null)
                return NotFound();

            // Update entity
            student.Name = model.Name;
            student.Email = model.Email;
            student.Age = model.Age;
            student.Address = model.Address;
            student.ImageURL = model.ImageURL;
            student.DepartmentId = model.DepartmentId;

            await _studentService.UpdateAsync(student);

            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        //  Student/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var student = await _studentService.GetByIdAsync(id);

            if (student == null)
                return NotFound();

            await _studentService.DeleteAsync(id);

            return RedirectToAction("Index");
        }

        #endregion


    }
}

School.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    Layout = null;
    var title = ViewData["Title"] ?? "Dashboard";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@title - School.Presentation</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/vendor/fontawesome-free/css/all.min.css" asp-append-version="true" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,600,700,800,900" rel="stylesheet">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css" asp-append-version="true" />

    <!-- SB Admin 2 -->
    <link rel="stylesheet" href="~/css/sb-admin-2.min.css" asp-append-version="true" />

    <!-- Site Custom Styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        @* ✅ Check if user is logged in *@
        @if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            @* ✅ If Instructor: Show Sidebar Dashboard *@
            if (User.IsInRole("INSTRUCTOR"))
            {
                <!-- Sidebar -->
                <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                    <!-- Sidebar - Brand -->
                    <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                        <div class="sidebar-brand-icon rotate-n-15">
                            <i class="fas fa-graduation-cap"></i>
                        </div>
                        <div class="sidebar-brand-text mx-3">Instructor Dashboard</div>
                    </a>

                    <hr class="sidebar-divider my-0" />

                    <!-- Dashboard -->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>

                    <hr class="sidebar-divider" />

                    <div class="sidebar-heading">Management</div>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Course" asp-action="Index">
                            <i class="fas fa-book-open"></i>
                            <span>Courses</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Student" asp-action="Index">
                            <i class="fas fa-user-graduate"></i>
                            <span>Students</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Department" asp-action="Index">
                            <i class="fas fa-building"></i>
                            <span>Departments</span>
                        </a>
                    </li>

                    <hr class="sidebar-divider d-none d-md-block" />

                    <!-- Logout -->
                    <li class="nav-item text-center mt-3">
                        <form asp-controller="Account" asp-action="SignOut" method="get" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm">
                                <i class="fas fa-sign-out-alt me-1"></i> Logout
                            </button>
                        </form>
                    </li>
                </ul>
                <!-- End of Sidebar -->
            }
            else if (User.IsInRole("STUDENT"))
            {
                @* ✅ If Student: Show Top Navbar *@
                <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
                    <div class="container-fluid">
                        <a class="navbar-brand fw-bold" asp-controller="Home" asp-action="Index">Student Portal</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Course" asp-action="Index">My Courses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Department" asp-action="Index">Departments</a>
                                </li>
                            </ul>

                            <form asp-controller="Account" asp-action="Logout" method="post" class="d-flex">
                                <button type="submit" class="btn btn-outline-danger">Logout</button>
                            </form>
                        </div>
                    </div>
                </nav>
            }
        }

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <div class="container-fluid mt-4">
                    @RenderBody()
                </div>
            </div>

            <!-- Footer -->
            <footer class="sticky-footer bg-white mt-auto">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>&copy; @DateTime.Now.Year - School.Presentation</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <!-- Scripts -->
    <script src="~/vendor/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/vendor/jquery-easing/jquery.easing.min.js" asp-append-version="true"></script>
    <script src="~/js/sb-admin-2.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>